### ISSUE TITLE
os.environ["HOST"]

### ISSUE THREAD

**Issue by wangemgnbo** [samirsaliba/price-sentinel#3]
Traceback (most recent call last):
  File "E:/Project/price-sentinel-main/price_sentinel/runner.py", line 115, in <module>
    price_sentinel = PriceSentinel()
  File "E:/Project/price-sentinel-main/price_sentinel/runner.py", line 21, in __init__
    self.HOST = os.environ["HOST"]
  File "D:\Anaconda\envs\Spider_redis\lib\os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'HOST'

How to solve this local database?

**Comment by samirsaliba** [comment]
Hi! So far I've only used a local database for development, but you could set this environmental variable to any mysql database you´d like. Do you have a mysql db instance running somewhere?
Also, this is the command I use to run the application: "python3 -m price_sentinel.runner". Has to be this way for the relative imports to work.
I should've added a README to the project but I thought nobody would come check it so soon.
Requirements.txt is missing pandas too, I changed it but haven't pushed yet.

If you're serious about running it, let me know and I'll help you out setting everything up :)
It's still in super early development so I'm sorry for the lack of explanation and guides.

**Comment by samirsaliba** [comment]
Hey @wangemgnbo, here's the [README](https://github.com/samirsaliba/price-sentinel#readme). I've added some explanation about the project and its limitations. Also added how to setup and run the application :) 
I'll mark this issue as closed but feel 100% free to ask for further explanations and help, ok? 
And sorry for adding this readme so late.
